export const SET = "SET";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const DELETE_ALL = "DELETE_ALL";
export const SET_STORE_PRODUCTS = "SET_STORE_PRODUCTS";
export const ADD_SHIPPING = "ADD_SHIPPING";
export const CLEAR_CART = "CLEAR_CART";
export const ADD_PAYMENT = "ADD_PAYMENT";
export const SET_SINGLE_ITEM = "SET_SINGLE_ITEM";
export const SET_ORDER_READY = "SET_ORDER_READY";
export const SET_TOTAL = "SET_TOTAL";

export const SET_NOT_ACTIVE_ORDERS = "SET_NOT_ACTIVE_ORDERS";
export const SET_NOT_ACTIVE_ORDERS_INFO = "SET_NOT_ACTIVE_ORDERS_INFO";

