

export const SET_PRODUCTS = "SET_PRODUCTS";



export const SINGLE_PRODUCT = "SINGLE_PRODUCT";
export const CLEAR_SINGLE_PRODUCT = "CLEAR_SINGLE_PRODUCT";



export const SET_IN_CART_ITEMS = "SET_IN_CART_ITEMS";


